// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TemplateService.Infrastructure.Persistence.Providers.Postgresql;

#nullable disable

namespace TemplateService.Infrastructure.Persistence.Providers.Postgresql.Migrations
{
    [DbContext(typeof(TemplatePostgresqlDbContext))]
    [Migration("20230905104722_TemplatePostgresqlDbContext_v0.0.1")]
    partial class TemplatePostgresqlDbContext_v001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("XXATACH_TMP")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TemplateService.Domain.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("TMP_Documents", "XXATACH_TMP", t =>
                        {
                            t.HasComment("Документы");
                        });
                });

            modelBuilder.Entity("TemplateService.Domain.Entities.MetaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("MetaTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MetaTypeId");

                    b.ToTable("TMP_Metas", "XXATACH_TMP", t =>
                        {
                            t.HasComment("Мета-описание документа");
                        });
                });

            modelBuilder.Entity("TemplateService.Domain.Entities.MetaTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TMP_MetaTypes", "XXATACH_TMP", t =>
                        {
                            t.HasComment("Тип мета-данных");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ID документа в СЭД АТАЧ",
                            Name = "atachdocumentid"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Регистрационный номер",
                            Name = "regnumber"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Дата регистрации",
                            Name = "regdate"
                        });
                });

            modelBuilder.Entity("TemplateService.Domain.Entities.MetaEntity", b =>
                {
                    b.HasOne("TemplateService.Domain.Entities.DocumentEntity", "Document")
                        .WithMany("Metas")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TemplateService.Domain.Entities.MetaTypeEntity", "MetaType")
                        .WithMany("Metas")
                        .HasForeignKey("MetaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("MetaType");
                });

            modelBuilder.Entity("TemplateService.Domain.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("TemplateService.Domain.Entities.MetaTypeEntity", b =>
                {
                    b.Navigation("Metas");
                });
#pragma warning restore 612, 618
        }
    }
}
