#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5124
EXPOSE 3119

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TemplateService/TemplateService.csproj", "TemplateService/"]
RUN dotnet restore "TemplateService/TemplateService.csproj"
COPY . .
WORKDIR "/src/TemplateService"
RUN dotnet build "TemplateService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TemplateService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TemplateService.dll"]